### ISSUE TITLE
Auto reconnect is not aggressive enough

### ISSUE THREAD

**Issue by TheKrafter** [azymohliad/watchmate#59]
After about 30 minutes to an hour of normal usage, the Watchmate eventually disconnects from the pinetime and does not reconnect, until I reopen the app and manually reacan.

This might be fixed by the intermittent scanning mechanism you referenced in #58.

Device: OnePlus 6
Host OS: postmarketOS edge
InfiniTime Version: 1.14.0
Watchmate Version: v0.5.1 (native package)

**Comment by azymohliad** [comment]
Hi! I've pushed some bluetooth-related fixes in #62, and I think it might be related to this issue too.

I want to include some more fixes and additions into the next release and test it more, so I'm not sure when I'm gonna release it. But if you'd like to try it earlier, you can install [this test build from Flathub CI](https://github.com/flathub/io.gitlab.azymohliad.WatchMate/pull/12):

```
flatpak install https://dl.flathub.org/build-repo/87429/io.gitlab.azymohliad.WatchMate.flatpakref
```

**Comment by azymohliad** [comment]
> I tried to collect logs with `flatpak run io.gitlab.azymohliad.WatchMate > watchmate-app.log 2>&1` however there was no output in the file

Hi! My guess is that WatchMate was already running in the background, so this command merely brought it to foreground. If you click "Quit" from the menu or press Ctrl+Q, then this command should collect the logs properly

**Comment by magic-ian** [comment]
Right on, that was it. Here are the logs. 

Line 1 is when the app first starts. Disconnect occurs with the unresolved GATT services, then it goes into device discovery mode, staying there until intervention. Clicking the device in the UI causes the device discovery to stop and successfully connect.

[watchmate.log](https://github.com/azymohliad/watchmate/files/15138383/watchmate.log)

**Comment by magic-ian** [comment]
One other addition for context in case it helps. I've been running Watchmate from a desktop (since Linux mobile you have to choose still between battery life via suspend, or a continuous connection with frequent recharges), and the watch is always within range, but I still have these disconnection issues.
